version: "3"

services:

  db:
    container_name: db
    image: "postgres:13"
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - result-tier
      - back-tier

  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    environment:
      - POLL_HOSTNAME=poll
      - WORKER_HOSTNAME=worker
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  result:
    container_name: result
    build: ./result
    restart: always
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier

  poll:
    container_name: poll
    build: ./poll
    restart: always
    environment:
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier

  worker:
    container_name: worker
    build: ./worker
    restart: always
    environment:
      - DB_HOSTNAME=db
      - REDIS_HOSTNAME=redis
    depends_on:
      - redis
      - db
    networks:
      - back-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: